# Generated by Django 4.2.5 on 2023-10-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="AnimeName",
                    ),
                ),
                (
                    "release_date",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ReleaseDate",
                    ),
                ),
                ("release_year", models.IntegerField()),
                (
                    "episode_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="NumOfEpisodes"
                    ),
                ),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="AuthorName",
                    ),
                ),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_num", models.IntegerField()),
                (
                    "chapter_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("page_count", models.IntegerField(blank=True, null=True)),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("episode_num", models.IntegerField()),
                (
                    "episode_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("length", models.IntegerField(blank=True, null=True)),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="LikeAnime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="LikeManga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="Manga",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="MangaName",
                    ),
                ),
                (
                    "release_date",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ReleaseDate",
                    ),
                ),
                ("release_year", models.IntegerField()),
                (
                    "chapter_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="NumOfChapters"
                    ),
                ),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="Manga_Tag",
            fields=[
                (
                    "tag",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="TagName",
                    ),
                ),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="RateAnime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="RateManga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userrate", models.FloatField()),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="ReadStatusManga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField()),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="SetTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="Studio",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="StudioName",
                    ),
                ),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Email",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="WatchEpisodeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watch_time", models.IntegerField(blank=True, null=True)),
                ("date", models.DateField(auto_now=True, null=True)),
                (
                    "status",
                    models.IntegerField(help_text="Same as status in WatchStatus"),
                ),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="WatchStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField()),
            ],
            options={"managed": False,},
        ),
    ]
